In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
#how many types of species which i want to predict
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X=df.drop('species',axis=1)
y=df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
"""For cross-validation we do not need to use the train test split."""

'For cross-validation we do not need to use the train test split.'

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_knn.score(X_test,y_test)
#If I am getting the Model Score  of 100% accuracy, then my model is overfit.

1.0

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma= 'auto')#hyperplane ke decision boundary ke andar koi data aajata hai to usko kehte hai 'c' penalty

In [ ]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
"""cross validation can reduce the over fitting of our model"""

'cross validation can reduce the over fitting of our model'

In [ ]:
"""How can we use the parameters to its best? we will see in Grid search CV"""

'How can we use the parameters to its best? we will see in Grid search CV'

In [ ]:
#now lets use the grid search cv

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False)

In [ ]:
"""Cross-validation has its own built-in scissor hands—it automatically splits, rotates, and tests your data in cycles, so you don't have to slice it manually beforehand."""

"Cross-validation has its own built-in scissor hands—it automatically splits, rotates, and tests your data in cycles, so you don't have to slice it manually beforehand."

In [ ]:
#We are using grid search cv  and then we are checking by applying in svm hyperparameters. How much hour model performances is measured

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00222874, 0.00194793, 0.00218315, 0.00159297, 0.00164185,
        0.00158691, 0.00166078, 0.00164371]),
 'std_fit_time': array([5.19178647e-04, 4.01761422e-04, 2.55353907e-04, 6.24896142e-05,
        4.33330867e-05, 3.63877057e-05, 1.78463274e-05, 1.35494887e-04]),
 'mean_score_time': array([0.00161786, 0.00136423, 0.00172534, 0.00121374, 0.00120754,
        0.00119972, 0.00122299, 0.00132251]),
 'std_score_time': array([4.90783852e-04, 1.58198444e-04, 4.79105480e-04, 3.80483186e-05,
        1.26585672e-05, 2.90319045e-05, 2.49229422e-05, 1.59500996e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002229,0.000519,0.001618,0.000491,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001948,0.000402,0.001364,0.000158,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002183,0.000255,0.001725,0.000479,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001593,0.000062,0.001214,0.000038,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001642,0.000043,0.001208,0.000013,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.001587,0.000036,0.001200,0.000029,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.001661,0.000018,0.001223,0.000025,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001644,0.000135,0.001323,0.000160,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
#interested- which parameter of c and which parameter of kernel is giving the best results

In [ ]:
results[['param_C','param_kernel','mean_test_score']]
#mean_test_score == accuracy

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter=4,cv = 5,return_train_score = False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       30       linear         0.960000
2       30          rbf         0.960000
3       20          rbf         0.966667